/* Generated by AN DISI Unibo */
package it.unibo.ctxRadar;

import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evhr extends AbstractEvhr {
	public Evhr(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds) throws Exception {
		super(name, myCtx, outEnvView, eventIds);
	}
}
