/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.photoreceiver;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.xml.bind.DatatypeConverter;

import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.mqtt.MqttUtils;

public class Photoreceiver extends AbstractPhotoreceiver {
	private MqttUtils mqtt = MqttUtils.getMqttSupport(this);
	private int counter = 1;
	
	public Photoreceiver(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	
	public void connectAndSubscribe() throws Exception {
		String clientid = "photoreceiver";
		String brokerAddr = "tcp://broker.hivemq.com:1883";
		String topic = "unibo/mqtt/robotbagnoli";
		this.mqtt.connect(this, clientid, brokerAddr, topic);
		this.mqtt.subscribe(this, clientid, brokerAddr, topic);
	}
	
	public void saveMqttPhoto(String photo) {
		ByteArrayInputStream bis = new ByteArrayInputStream(DatatypeConverter.parseBase64Binary(photo));
		BufferedImage image;
		try {
			image = ImageIO.read(bis);
			bis.close();
			File outputfile = new File("ioRobotPhoto" + this.counter + ".jpg");
			ImageIO.write(image, "jpg", outputfile);
			this.counter++;
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	
	
}
