/* Generated by AN DISI Unibo */
package it.unibo.robot_actor;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.xml.bind.DatatypeConverter;

import org.eclipse.paho.client.mqttv3.MqttException;

import com.hopding.jrpicam.RPiCamera;
import com.hopding.jrpicam.enums.Exposure;
import com.hopding.jrpicam.exceptions.FailedToRunRaspistillException;

import it.unibo.bls.highLevel.interfaces.IDevLed.LedColor;
import it.unibo.bls.raspberry.components.DeviceLedPi4j;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.mqtt.MqttUtils;

public class Robot_actor extends AbstractRobot_actor {
	protected DeviceLedPi4j ledpi4j;
	private MqttUtils mqtt = MqttUtils.getMqttSupport(this);
	private BlinkAsynch blink;
	protected RPiCamera piCamera;
	private int counter = 1;
	
	private String clientId = "ioRobotBNP";
	private String brokerAddr = "tcp://test.mosquitto.org:1883";
	private String topic = "unibo/mqtt/ioRobotBNP";

	public Robot_actor(String actorId, QActorContext myCtx, IOutputEnvView outEnvView) throws Exception {
		super(actorId, myCtx, outEnvView, it.unibo.qactors.QActorUtils.robotBase);
	}

	public void createPi4jLed() {
		try {
			println("Led createPi4jLed STARTS ");
			this.ledpi4j = new DeviceLedPi4j("led0", this.outEnvView, LedColor.RED, 23);
			this.blink = new BlinkAsynch("blinker", this.outEnvView, ledpi4j);

		} catch (Exception e) {
			println("ERROR " + e.getMessage());
		}
	}

	public void startBlink() {
		this.blink.activate();
	}

	public void stopBlink() {
		this.blink.suspendWork();
	}

	public void createPiCamera() {
		try {
			println("createPiCamera START");
			this.piCamera = new RPiCamera("");
			this.piCamera.setWidth(500).setHeight(500) // Set Camera width and height
					.setExposure(Exposure.AUTO) // Set Camera's exposure.
					.setTimeout(2) // Set Camera's timeout.
					.setAddRawBayer(true) // Add Raw Bayer data to image files
					.setHorizontalFlipOn() // Flip orizzontale automatico
					.setRotation(180); // Rotazione immagine automatica
			
			println("createPiCamera END");

		} catch (FailedToRunRaspistillException e) {
			println("ERROR " + e.getMessage());
		}
	}

	private BufferedImage takePhoto() {
		BufferedImage image = null;
		try {
			println("ACQUISIZIONE FOTO IN CORSO...");
			image = this.piCamera.takeBufferedStill(); 
			println("FOTO ACQUISITA");
		} catch (IOException | InterruptedException e) {
			println("ERROR " + e.getMessage());
		}
		return image;
	}

	public void connectToSend() throws MqttException {
		this.mqtt.connect(this, this.clientId, this.brokerAddr, this.topic);
	}

	public void sendMsgMqtt() {
		try {
			BufferedImage bi = this.takePhoto();
			ByteArrayOutputStream os = new ByteArrayOutputStream();
			ImageIO.write(bi, "jpg", os);
			String messageBase64 = DatatypeConverter.printBase64Binary(os.toByteArray());
			os.close();
			String messageToSend = "msg( photograph, dispatch, " +  this.getName() + ", " + this.getName().replace("_ctrl", "") + ", " + "ph(\"" + messageBase64 + "\")" + ", " + this.counter++ + ")";
			this.mqtt.publish(this, this.clientId, this.brokerAddr, this.topic, messageToSend, 1, false);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

}
