/* Generated by AN DISI Unibo */ 
package it.unibo.robot_actor;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

//
public class Robot_actor extends AbstractRobot_actor { 
	public Robot_actor(String actorId, QActorContext myCtx, IOutputEnvView outEnvView ) throws Exception{
		super(actorId,myCtx,outEnvView ,it.unibo.qactors.QActorUtils.robotBase );
	}
}
