/* Generated by AN DISI Unibo */ 
package it.unibo.robot_actor;
import it.unibo.bls.highLevel.interfaces.IDevLed.LedColor;
import it.unibo.bls.raspberry.components.DeviceLedPi4j;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Robot_actor extends AbstractRobot_actor {
	protected DeviceLedPi4j ledpi4j;
	private BlinkAsynch blink;
	
	public Robot_actor(String actorId, QActorContext myCtx, IOutputEnvView outEnvView ) throws Exception{
		super(actorId,myCtx,outEnvView ,it.unibo.qactors.QActorUtils.robotBase );
	}
	
	public void createPi4jLed(int pinNum) {
		try {
			println("Led createPi4jLed STARTS " + pinNum);
			this.ledpi4j = new DeviceLedPi4j("led0", outEnvView, LedColor.RED, pinNum);
			this.blink = new BlinkAsynch("blinker",outEnvView, ledpi4j);
			
		} catch (Exception e) {
			println("ERROR " + e.getMessage());
		}
	}
	
	public void startBlink(){
		this.blink.activate();
	}
	
	public void stopBlink(){
		this.blink.suspendWork();
	}
}
