/* Generated by AN DISI Unibo */
/*
This code is generated only ONCE
*/
package it.unibo.radargui;

import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Radargui extends AbstractRadargui {
	protected RadarControl radarControl;

	public Radargui(String actorId, QActorContext myCtx, IOutputEnvView outEnvView) throws Exception {
		super(actorId, myCtx, outEnvView);
	}

	public boolean activateGui() throws Exception {
		println(this.getName() + " activateGui ");
		radarControl = new RadarControl(myCtx, outEnvView);
		return true;
	}

	public void sendDataToGui(int distance, int angle) {
		println("sendDataToGui: " + distance + " " + angle);
		// String first = distance.replaceAll("[^0-9]+", " ");
		// List<String> lista = Arrays.asList(first.trim().split(" "));
		radarControl.update(Integer.toString(distance), Integer.toString(angle));
	}

	// public void connectAndSubscribe(String clientid, String brokerAddr,
	// String topic) throws Exception{
	// println(this.getName() + " connectAndSubscribe " );
	// this.mqtt.connect(this, clientid, brokerAddr, topic);
	// this.mqtt.subscribe(this, clientid, brokerAddr, topic);
	// }
}
