/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.robotsonar;
import java.io.BufferedReader;

import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.QActorUtils;

public class Robotsonar extends AbstractRobotsonar { 
	private BufferedReader readerC;

	public Robotsonar(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	
	public void startSonarC() {
		try {
			println("Start Robot Sonar C");
			Process p = Runtime.getRuntime().exec("sudo ./SonarAlone");
			this.readerC = new BufferedReader(new java.io.InputStreamReader(p.getInputStream()));
			println("Process in C STARTED: " + this.readerC);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public void getDistanceFromSonar() {
		try {
			String strDistance = this.readerC.readLine();
			int distance = Integer.parseInt(strDistance);
			println("RobotSonar " + distance);
			if (distance < 5) {
				QActorUtils.raiseEvent(this.getQActorContext(), "sensor", "obstacle", "obstacle(" + distance + ")");
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
