/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.alarmhandler;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Alarmhandler extends AbstractAlarmhandler { 
	public Alarmhandler(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
}
